;;; GNU Guix --- Functional package management for GNU
;;; Copyright © 2025 Noé Lopez <noelopez@free.fr>
;;;
;;; This file is part of GNU Guix.
;;;
;;; GNU Guix is free software; you can redistribute it and/or modify it
;;; under the terms of the GNU General Public License as published by
;;; the Free Software Foundation; either version 3 of the License, or (at
;;; your option) any later version.
;;;
;;; GNU Guix is distributed in the hope that it will be useful, but
;;; WITHOUT ANY WARRANTY; without even the implied warranty of
;;; MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
;;; GNU General Public License for more details.
;;;
;;; You should have received a copy of the GNU General Public License
;;; along with GNU Guix.  If not, see <http://www.gnu.org/licenses/>.

;;; This manifest is a list of packages that user care about (collected via an
;;; online form).  It corresponds to the “Important packages” of GCD 005.

(specifications->manifest
 (list
  "0ad"
  "agda"
  "alacritty"
  "ardour"
  "autoconf"
  "automake"
  "blender"
  "borg"
  "btrfs-progs"
  "certbot"
  "chez-scheme"
  "clang-toolchain"
  "cryptsetup"
  "dillo"
  "direnv"
  "docker-cli"
  "dovecot"
  "emacs"
  "emacs-exwm"
  "emacs-pgtk"
  "evince"
  "fcitx5"
  "file"
  "fish"
  "foot"
  "fzf"
  "gajim"
  "gallery-dl"
  "gcc-toolchain"
  "getmail6"
  "gettext"
  "ghc-xmonad-contrib"
  "gimp"
  "git"
  "gmp"
  "gnome"
  "gnupg"
  "godot"
  "gpaste"
  "guile"
  "guile-json"
  "hatch"
  "help2man"
  "helvum"
  "hexchat"
  "hyprland"
  "icecat"
  "idris"
  "imagemagick"
  "imapfilter"
  "jami"
  "k3b"
  "kakoune"
  "keepassxc"
  "krita"
  "ksoloti-patcher"
  "libreoffice"
  "librewolf"
  "libsecret"
  "libtool"
  "libvirt"
  "llama-cpp"
  "mariadb"
  "luanti"
  "mpc"
  "mpfr"
  "mplayer"
  "mpv"
  "mullvadbrowser"
  "neovim"
  "nginx"
  "niri"
  "nix"
  "node"
  "notmuch"
  "obs"
  "offlineimap3"
  "opencv"
  "openmpi"
  "opensmtpd"
  "openssh"
  "openttd"
  "pandoc"
  "password-store"
  "pavucontrol"
  "php"
  "picard"
  "pipewire"
  "pkg-config"
  "plasma"
  "plasma-desktop"
  "po4a"
  "podman"
  "postgresql"
  "python"
  "python-lxml"
  "python-pycryptodome"
  "qemu"
  "ranger"
  "retroarch"
  ;;"rocm"
  "rofi"
  "rspamd"
  "rsync"
  "screen"
  "slurm"
  "sqlite"
  "sqlitebrowser"
  "strace"
  "strawberry"
  "syncthing"
  "taisei"
  "telegram-desktop"
  "texlive-babel"
  "texlive-babel-english"
  "texlive-babel-french"
  "texlive-babel-german"
  "texlive-collection-latex"
  "texlive-collection-latexrecommended"
  "texlive-collection-xetex"
  "texlive-pdfjam"
  "tmux"
  "tuba"
  "ungoogled-chromium"
  "unison"
  "unzip"
  "uv"
  "viewnior"
  "virt-manager"
  "waybar"
  "wine"
  "wine64"
  "wireguard-tools"
  "xmobar"
  "xmonad"
  "xournal"
  "xournalpp"
  "xpdf"
  "yt-dlp"
  "zig"
  "zip"
  "zsh"))
