#!/bin/sh
# Authenticate the repo upon 'git pull' and similar.
if ! git config guix.authentication.introduction-commit; then
    exec guix git authenticate 9edb3f66fd807b096b48283debdcddccfea34bad \
         "BBB0 2DDF 2CEA F6A8 0D1D  E643 A2A0 6DF2 A33A 54FA" \
         -k origin/keyring
else
    exec guix git authenticate
fi
